from enum import Enum


class ErrorCode(Enum):
    UNKNOWN_ERROR = ("UNKNOWN_ERROR",)
    BAD_MESSAGE = ("BAD_MESSAGE",)
    SYNTAX_ERROR = ("SYNTAX_ERROR",)
    REPOSITORY_ERROR = ("REPOSITORY_ERROR",)
    PUBSUB_ERROR = ("PUBSUB_ERROR",)
    EXTERNAL_ERROR = ("EXTERNAL_ERROR",)
    REDIS_ERROR = ("REDIS_ERROR",)
    RETRY_LIMIT_ERROR = ("RETRY_LIMIT_ERROR",)
    RETRY_ERROR = ("RETRY_ERROR",)
    ERR_CACHE_ACCESS = ("GOT: ERR_CACHE_ACCESS",)
    ERR_READING_RESPONSE = ("GOT: ERR_READING_RESPONSE_STREAM",)
    ERR_TIMEOUT = ("GOT: ERR_TIMEOUT",)
    GOT_UNKNOWN_ERROR = ("GOT_UNKNOWN_ERROR",)


class StatusCode(str):
    OK = (200,)
    CREATED = (201,)
    ACCEPTED = (202,)
    NO_CONTENT = (204,)
    BAD_REQUEST = (400,)
    UNAUTHORIZED = (401,)
    FORBIDDEN = (403,)
    NOT_FOUND = (404,)
    PRECONDITION_FAILED = (412,)
    I_AM_A_TEAPOT = (418,)
    UNPROCESSABLE_ENTITY = (422,)
    FAILED_DEPENDENCY = (424,)
    TOO_EARLY = (425,)
    PRECONDITION_REQUIRED = (428,)
    INTERNAL_SERVER_ERROR = (500,)
    BAD_GATEWAY = (502,)
    SERVICE_UNAVAILABLE = (503,)
