repos:
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black

  - repo: https://github.com/timothycrosley/isort
    rev: 5.13.2
    hooks:
      - id: isort
        additional_dependencies: [ toml ]

  - repo: https://github.com/pylint-dev/pylint
    rev: v3.3.1
    hooks:
      - id: pylint
        language: python
        additional_dependencies:
          - fastapi
          - injector
          - psycopg2-binary
          - pytest
          - pytest-postgresql
          - python-dotenv
          - requests
          - redis
          - google-cloud-storage
          - pandas
        entry: poetry run pylint
        args: [ "--output-format=colorized" ]
        files: \.py$

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements
      - id: check-toml
      - id: check-yaml
      - id: fix-byte-order-marker
      - id: check-added-large-files
      - id: detect-private-key

  # Commit message validation
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.14.1  # Use the latest stable version
    hooks:
      - id: commitizen
        stages: [ commit-msg ]

  # Custom branch name validation
  - repo: local
    hooks:
      - id: validate-branch-name
        name: Branch name must follow the pattern 'feature/*'
        entry: ./precommit/validate_branch_name.sh
        language: script
        stages: [ commit-msg ]
