version: '3.8'
services:
  postgres:
    image: postgres:15-alpine # If you want to do complex things, remove alpine (It's a lightweight version)
    container_name: test_postgres
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.5"
    volumes:
      - ./sql-test-docker/init.sql:/docker-entrypoint-initdb.d/init.sql
